### ISSUE TITLE
Request using Gulp and Libsass

### ISSUE THREAD

**Issue by rizqinizamil** [robwierzbowski/generator-jekyllrb#133] opened 2015-02-03 00:36 UTC
I love this generator, if you don't mind can you create Gulp version and also using Libsass? :)

**Comment by robwierzbowski** [comment] 2015-02-03 02:30
It is a difficult task. You should give it a shot!

On Monday, February 2, 2015, Rizqi Nizamil Putra <notifications@github.com>
wrote:

> I love this generator, if you don't mind can you create Gulp version and
> also using Libsass? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robwierzbowski/generator-jekyllrb/issues/133>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by dnozay** [comment] 2015-02-06 08:28
pull requests welcome.

**Comment by dnozay** [comment] 2015-02-06 08:30
dupe of #116

**Closed by dnozay** 2015-02-06 08:30 UTC
Labels: pull request welcome
