### ISSUE TITLE
generator crashes due to misnamed directory

### ISSUE THREAD

**Issue by JonathanReeve** [robwierzbowski/generator-jekyllrb#136] opened 2015-02-04 19:25 UTC
After configuring a Jekyll site with HTML5 Boilerplate, the generator fails with the error: 

    Error: ENOENT, no such file or directory '/home/jreeve/.npm-packages/lib/node_modules/generator-jekyllrb/app/templates/conditional/template-h5bp/index.html'

This is probably because there is no directory called `template-h5bp`. There is a directory called `template-H5BP`, however, and renaming that directory to `template-h5bp` fixes this problem.

**Comment by dnozay** [comment] 2015-02-04 21:35
fixed in 4f926b5c5208f03bf5d40be88a2d8721276a37fd. dupe of #132

**Closed by dnozay** 2015-02-04 21:35 UTC
